language: ruby
rvm:
- 2.0.0
- 1.9.3
- 1.8.7
env:
  global:
  - secure: tklYdNk9OVh9usXyyPlpsw7srJ+u9Py1Hyqv7YsB9iu5YfImXDE7xwiTTx42eI/MEyVzNFb5CLYYECrDB9e89u8yTnrsaPfvINf2feMrkk/q4wVIa/zt/fD/v5oucAvZ41E04YJBw+Kr/gQiEiZiwV8iQTRDnRBBFzXFR7i/Ye8=
  - secure: KqKfLVlg+yos3AVEeuvnk5UKY3SuF02nFHpll7KL1UXVoshLgTsTSdhNqaguJ7v8NyHUOqgoHI3WwM2QQQ2UMOsBhb933J9Y4nqWXM25ig2sjfJtLaACc5edmY09VU80GMMq29X5j9ikw4VCoE1tl5Yts0JZH0ks8z1Q1pXNDnc=
